### ISSUE TITLE
[Bug] - java.lang.IllegalStateException: TextAttributeKey(name:'DEFAULT_SECONDARY_KEYWORD_WITH_BG',

### ISSUE THREAD

**Issue by p000ic** [dinbtechit/vscode-theme#42]
## Platform & Language Details (please complete the following information):
- Platform: GoLand 2022.3
- Platform Version: GO-223.7571.176
- Language: Go
- Version 1.18.8

### Extra info
- Build #GO-223.7571.176, built on November 29, 2022
- Runtime version: 17.0.5+1-b653.14 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- Windows 11 10.0
- Non-Bundled Plugins:
    com.intellij.ideolog (203.0.30.0)
    Batch Scripts Support (1.0.13)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    org.jetbrains.plugins.sass (223.7571.142)
    org.rust.lang (0.4.184.5057-223)
    org.toml.lang (223.7571.117)
    com.intellij.plugins.vscodekeymap (223.7571.113)
    ski.chrzanow.foldableprojectview (1.1.4)
    PlantUML integration (5.20)
    Dart (223.7571.203)
    PythonCore (223.7571.182)
    mobi.hsz.idea.gitignore (4.4.4)
    intellij.prettierJS (223.7571.142)
    org.jetbrains.plugins.vue (223.7571.212)
    com.previewjs.intellij.plugin (1.16.1)
    ru.adelf.idea.dotenv (2022.3)
    com.github.dinbtechit.vscodetheme (1.7.4)
    com.ypwang.plugin.go-linter (1.6.2)

## Jetbrains Screenshot
<img width="790" alt="image" src="https://user-images.githubusercontent.com/62242610/206571382-d04b456f-b24d-4566-8050-03d20065f36a.png">

## Additional context/Logs
```log
java.lang.IllegalStateException: TextAttributeKey(name:'DEFAULT_SECONDARY_KEYWORD_WITH_BG', fallbackAttributeKey:'DEFAULT_KEYWORD')  was already registered with the other fallback attribute key: JS.KEYWORD (fallbackKey: DEFAULT_KEYWORD)
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:226)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:212)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1940)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:212)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:199)
	at com.github.dinbtechit.vscodetheme.annotators.GoAnnotator.<clinit>(GoAnnotator.kt:17)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:956)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1012)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:55)
	at com.intellij.serviceContainer.LazyExtensionInstance.getInstance(LazyExtensionInstance.java:44)
	at com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance(BaseKeyedLazyInstance.java:38)
	at com.intellij.openapi.util.KeyedExtensionCollector.instantiate(KeyedExtensionCollector.java:177)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensionsFromExtensionPoint(KeyedExtensionCollector.java:164)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:139)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:147)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:16)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:111)
	at com.intellij.lang.LanguageExtension.collectAllForLanguage(LanguageExtension.java:125)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:116)
	at com.intellij.lang.LanguageExtension.allForLanguageOrAny(LanguageExtension.java:160)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.createAnnotators(DefaultHighlightVisitor.java:212)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.lambda$new$0(DefaultHighlightVisitor.java:38)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:123)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:304)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by p000ic** [comment]
Got the update.
