### ISSUE TITLE
[Bug] - Provide support for InteliJ IDEA new UI

### ISSUE THREAD

**Issue by nathan-i-martin** [dinbtechit/vscode-theme#78]
Greetings! I'd like to request that some sort of support is added for the new InteliJ IDEA UI! I've been using the new UI for a while now and I love it! The only issue is that vscode-theme doesn't work on it!
I would love if support could be added!

## Additional context
When the plugin boots up it dies because of the following exception. Hopefully, this helps!
```java
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at com.github.dinbtechit.vscodetheme.VSCodeThemeManager.switchToVSCodeTheme(VSCodeThemeManager.kt:58)
	at com.github.dinbtechit.vscodetheme.VSCodeThemeManager.switchToVSCodeTheme$default(VSCodeThemeManager.kt:41)
	at com.github.dinbtechit.vscodetheme.startup.VSCodeStartupNotifyActivity.runActivity(VSCodeStartupNotifyActivity.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:328)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$3.invoke$lambda$0(StartupManagerImpl.kt:284)
	at com.intellij.openapi.project.SmartModeScheduler.doRun(SmartModeScheduler.kt:124)
	at com.intellij.openapi.project.SmartModeScheduler.runAllWhileSmart(SmartModeScheduler.kt:117)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by dinbtechit** [comment]
@nathan-i-martin  - Thank you for reporting this bug. It should work on new UI. I use new UI and have no issues.

Can you provide more info about your IDE?

1. Go to about Intellij or what ever IDE that you are using:
![image](https://github.com/dinbtechit/vscode-theme/assets/17984781/0c743b37-2618-463f-b401-ea3763615af4)

2. Copy and paste the details here: (Please remove any sensitive info:)
![image](https://github.com/dinbtechit/vscode-theme/assets/17984781/d51e4d2f-033f-405c-bb58-971a499bd089)

**Comment by nathan-i-martin** [comment]
hmm that's strange!
Okay, here's what mine says!
```
IntelliJ IDEA 2023.1.3 (Community Edition)
Build #IC-231.9161.38, built on June 20, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    Statistic (4.2.7)
    com.jetbrains.ChooseRuntime (1.2)
    com.nasller.CodeGlancePro (1.6.5)
    ru.adelf.idea.dotenv (2023.1)
    com.github.dinbtechit.vscodetheme (1.8.3)

Kotlin: 231-1.8.21-IJ9161.38
```

**Comment by dinbtechit** [comment]
Can you confirm if you see "VScode Dark Modern" in your settings -> Appearance & Behavior -> Appearance? If you do can you manually select it?

![image](https://github.com/dinbtechit/vscode-theme/assets/17984781/0fc85b29-8b7b-4f80-8bce-4637401e259e)

**Comment by nathan-i-martin** [comment]
🤦 looks like that's what I was missing, thank you! I guess when I loaded the new UI it reset my theme. I hadn't considered it would do that

**Comment by q-wertz** [comment]
Had the same issue with `1.8.3`

I activated the new UI some while ago and switched back.
After I read the previous posts I switched to another Theme and then back to `VSCode Dark Modern` and the error so far did not appear again.

**Comment by dinbtechit** [comment]
@q-wertz  - Are you able to provide a screencast of reproducing that error? I am not able to recreate it.

**Comment by q-wertz** [comment]
For me it was a one time issue…
Could not reproduce it, despite trying different workflows of enabling/disabling the new UI... Maybe also the update of PyCharm and/or the plugin played a role...
